# version: "3.9"
# docker-compose run --rm app sh -c "python manage.py runserver 0.0.0.0:8000"
# docker compose run --rm --service-ports app sh -c "python manage.py runserver 0.0.0.0:8000"
# docker compose run up
# docker compose build

# docker-compose build --no-cache --build-arg DEV=True
services:
  app:
    build:
      context: .
      args:
        DEV: ${DEV}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    expose:
      - "8000"
    networks:
      - my-network

  db:
    image: postgres:16-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - my-network

  nginx:
    image: nginx:latest
    container_name: django_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      - ./lckPick/.next:/app/lckPick/.next
    depends_on:
      - app
    networks:
      - my-network

  celery:
    container_name: celery
    build:
      context: .
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "celery -A core.celery worker --loglevel=info"
    depends_on:
      - app
      - redis
    deploy:
      resources:
        limits:
          memory: 512M  # 메모리 제한
          cpus: "0.5"   # CPU 제한
    networks:
      - my-network
      
  redis:
    image: redis:7.4.3-alpine
    ports:
      - "6379:6379"
    networks:
      - my-network


volumes:
  dev-db-data:

networks:
  my-network:
    external: true
