# Generated by Django 5.0.14 on 2025-05-08 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_ko', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('full_image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('icon_image_url', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoLUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('tag', models.CharField(blank=True, max_length=32, null=True)),
                ('tier', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=10)),
                ('lp', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PatchVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('release_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PositionChampion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MID', 'Mid'), ('ADC', 'Adc'), ('SUPPORT', 'Support')], max_length=20)),
                ('pick_count', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lol.champion')),
                ('patch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lol.patchversion')),
            ],
        ),
        migrations.CreateModel(
            name='TeamComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_count', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('adc', models.ForeignKey(limit_choices_to={'position': 'ADC'}, on_delete=django.db.models.deletion.CASCADE, related_name='adc_team_compositions', to='lol.positionchampion')),
                ('jungle', models.ForeignKey(limit_choices_to={'position': 'JUNGLE'}, on_delete=django.db.models.deletion.CASCADE, related_name='jungle_team_compositions', to='lol.positionchampion')),
                ('mid', models.ForeignKey(limit_choices_to={'position': 'MID'}, on_delete=django.db.models.deletion.CASCADE, related_name='mid_team_compositions', to='lol.positionchampion')),
                ('patch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lol.patchversion')),
                ('support', models.ForeignKey(limit_choices_to={'position': 'SUPPORT'}, on_delete=django.db.models.deletion.CASCADE, related_name='support_team_compositions', to='lol.positionchampion')),
                ('top', models.ForeignKey(limit_choices_to={'position': 'TOP'}, on_delete=django.db.models.deletion.CASCADE, related_name='top_team_compositions', to='lol.positionchampion')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.BigIntegerField(unique=True)),
                ('region', models.CharField(max_length=20)),
                ('blue_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_team_matches', to='lol.teamcomposition')),
                ('red_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_team_matches', to='lol.teamcomposition')),
            ],
        ),
        migrations.CreateModel(
            name='EsportsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sets', models.IntegerField(default=0)),
                ('patch', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blue_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blue_team_games', to='lol.team')),
                ('red_team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='red_team_games', to='lol.team')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='won_games', to='lol.team')),
                ('blue_composition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blue_compositions', to='lol.teamcomposition')),
                ('red_composition', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='red_compositions', to='lol.teamcomposition')),
            ],
        ),
        migrations.CreateModel(
            name='AdcSupportComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_count', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lol.patchversion')),
                ('adc', models.ForeignKey(limit_choices_to={'position': 'ADC'}, on_delete=django.db.models.deletion.CASCADE, related_name='adc_compositions', to='lol.positionchampion')),
                ('support', models.ForeignKey(limit_choices_to={'position': 'SUPPORT'}, on_delete=django.db.models.deletion.CASCADE, related_name='support_compositions', to='lol.positionchampion')),
            ],
            options={
                'unique_together': {('patch', 'adc', 'support')},
            },
        ),
        migrations.CreateModel(
            name='TopJungleMidComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_count', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('jungle', models.ForeignKey(limit_choices_to={'position': 'JUNGLE'}, on_delete=django.db.models.deletion.CASCADE, related_name='jungle_compositions', to='lol.positionchampion')),
                ('mid', models.ForeignKey(limit_choices_to={'position': 'MID'}, on_delete=django.db.models.deletion.CASCADE, related_name='mid_compositions', to='lol.positionchampion')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lol.patchversion')),
                ('top', models.ForeignKey(limit_choices_to={'position': 'TOP'}, on_delete=django.db.models.deletion.CASCADE, related_name='top_compositions', to='lol.positionchampion')),
            ],
            options={
                'unique_together': {('patch', 'top', 'jungle', 'mid')},
            },
        ),
    ]
