# Generated by Django 4.2.19 on 2025-02-28 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JungleChampion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_count', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jungle_champion', to='lol.champion', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MidChampion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_count', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mid_champion', to='lol.champion', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupportChampion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_count', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='support_champion', to='lol.champion', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopChampion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_count', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='top_champion', to='lol.champion', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdCarryChampion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_count', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ad_carry_champion', to='lol.champion', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_count', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('adc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_compositions', to='lol.adcarrychampion')),
                ('jungle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_compositions', to='lol.junglechampion')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_compositions', to='lol.midchampion')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_compositions', to='lol.supportchampion')),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_compositions', to='lol.topchampion')),
            ],
            options={
                'unique_together': {('top', 'jungle', 'mid', 'adc', 'support')},
            },
        ),
    ]
