# Generated by Django 5.0.14 on 2025-05-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoLUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puuid', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('tag', models.CharField(max_length=32)),
                ('tier', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=10)),
                ('lp', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
            ],
        ),
    ]
