# Generated by Django 5.0.14 on 2025-05-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patchversion',
            name='last_crawl_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='positionchampion',
            unique_together={('patch', 'champion', 'position')},
        ),
    ]
