# Generated by Django 4.2.19 on 2025-03-01 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('patch', models.CharField(max_length=10)),
                ('blue_team', models.CharField(max_length=100)),
                ('red_team', models.CharField(max_length=100)),
                ('winner', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='champion',
            name='ban_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MatchComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_blue_side', models.BooleanField()),
                ('is_winner', models.BooleanField()),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lol.teamcomposition')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lol.match')),
            ],
            options={
                'unique_together': {('match', 'is_blue_side')},
            },
        ),
    ]
