# Generated by Django 5.0.14 on 2025-05-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0002_loluser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loluser',
            name='name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='loluser',
            name='tag',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
