# Generated by Django 4.2.19 on 2025-03-01 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0002_match_champion_ban_count_matchcomposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('image_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='blue_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='blue_team_matches', to='lol.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='red_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='red_team_matches', to='lol.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='winner_matches', to='lol.team'),
        ),
    ]
