# Generated by Django 5.0.14 on 2025-05-10 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0002_patchversion_last_crawl_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MID', 'Mid'), ('ADC', 'Adc'), ('SUPPORT', 'Support')], max_length=20)),
                ('wins_a', models.IntegerField(default=0)),
                ('wins_b', models.IntegerField(default=0)),
                ('champion_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_a', to='lol.champion')),
                ('champion_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_b', to='lol.champion')),
                ('patch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lol.patchversion')),
            ],
            options={
                'unique_together': {('patch', 'position', 'champion_a', 'champion_b')},
            },
        ),
    ]
