# Generated by Django 5.0.14 on 2025-05-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0003_counterrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loluser',
            name='tier',
            field=models.CharField(max_length=32),
        ),
    ]
