# Generated by Django 5.0.14 on 2025-05-07 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0003_alter_loluser_name_alter_loluser_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdcSupportComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_count', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('adc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adc_support_compositions', to='lol.adcarrychampion')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adc_support_compositions', to='lol.patchversion')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adc_support_compositions', to='lol.supportchampion')),
            ],
            options={
                'unique_together': {('patch', 'adc', 'support')},
            },
        ),
        migrations.CreateModel(
            name='TopJungleMidComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_count', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('jungle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_jugle_mid_compositions', to='lol.junglechampion')),
                ('mid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_jugle_mid_compositions', to='lol.midchampion')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_jugle_mid_compositions', to='lol.patchversion')),
                ('top', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_jugle_mid_compositions', to='lol.topchampion')),
            ],
            options={
                'unique_together': {('patch', 'top', 'jungle', 'mid')},
            },
        ),
    ]
