# Generated by Django 5.0.14 on 2025-05-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0004_adcsupportcomposition_topjunglemidcomposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
