# Generated by Django 5.0.12 on 2025-03-04 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0005_match_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='blue_composition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blue_team_matches', to='lol.teamcomposition'),
        ),
        migrations.AddField(
            model_name='match',
            name='red_composition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='red_team_matches', to='lol.teamcomposition'),
        ),
        migrations.DeleteModel(
            name='MatchComposition',
        ),
    ]
