# Generated by Django 5.0.12 on 2025-03-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0006_match_blue_composition_match_red_composition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adcarrychampion',
            name='pick_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adcarrychampion',
            name='win_count',
            field=models.IntegerField(default=0),
        ),
    ]
