# Generated by Django 5.0.12 on 2025-03-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0007_adcarrychampion_pick_count_adcarrychampion_win_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='name_ko',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
