# Generated by Django 5.0.13 on 2025-03-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0008_champion_name_ko'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='image_url',
        ),
        migrations.AddField(
            model_name='champion',
            name='full_image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='champion',
            name='icon_image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
