# Generated by Django 5.0.14 on 2025-04-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0009_remove_champion_image_url_champion_full_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='ban_count',
        ),
    ]
