# Generated by Django 5.0.14 on 2025-04-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0010_remove_champion_ban_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('release_date', models.DateTimeField()),
            ],
        ),
    ]
