# Generated by Django 5.0.14 on 2025-04-30 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0011_patchversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('TOP', 'Top'), ('JUNGLE', 'Jungle'), ('MID', 'Mid'), ('ADC', 'Adc'), ('SUPPORT', 'Support')], max_length=20)),
                ('pick_count', models.IntegerField(default=0)),
                ('win_count', models.IntegerField(default=0)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_stats', to='lol.champion')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion_stats', to='lol.patchversion')),
            ],
            options={
                'unique_together': {('patch', 'champion', 'position')},
            },
        ),
    ]
