# Generated by Django 5.0.14 on 2025-04-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0012_championstat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='EsportsGame',
        ),
    ]
