# Generated by Django 5.0.14 on 2025-04-30 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lol', '0013_rename_match_esportsgame'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamcomposition',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='teamcomposition',
            name='patch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_compositions', to='lol.patchversion'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='esportsgame',
            name='blue_composition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='blue_team_matches_esports', to='lol.teamcomposition'),
        ),
        migrations.AlterField(
            model_name='esportsgame',
            name='red_composition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='red_team_matches_esports', to='lol.teamcomposition'),
        ),
        migrations.AlterUniqueTogether(
            name='teamcomposition',
            unique_together={('patch', 'top', 'jungle', 'mid', 'adc', 'support')},
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(unique=True)),
                ('region', models.CharField(max_length=20)),
                ('blue_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blue_team_matches', to='lol.teamcomposition')),
                ('red_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_team_matches', to='lol.teamcomposition')),
            ],
        ),
    ]
